Update demo-05-push-to-main.yml

diff --git a/.github/workflows/demo-05-push-to-main.yml b/.github/workflows/demo-05-push-to-main.yml
--- a/.github/workflows/demo-05-push-to-main.yml
+++ b/.github/workflows/demo-05-push-to-main.yml
@@ -1,28 +1,28 @@
-name: Demo 05 - Push To Main
+name: Demo 05 - Pull Request
 
 on:
-  workflow_dispatch:
-  push:
+  pull_request:
     branches: 
       - main
-
-permissions:
-  contents: read
-  actions: read
-  checks: write
   
 jobs:
-  build-app:
-    name: "Build App"
+  build-test-branch:
+    name: "Build and Test Of PR"
+
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v5
+
+    # - name: Make PR Fail
+    #  run: exit 1
+
+    - uses: actions/checkout@v4
+
       
-    - name: Setup .NET 8
-      uses: actions/setup-dotnet@v5
+    - name: Setup .NET Core 5
+      uses: actions/setup-dotnet@v4
       with:
-        dotnet-version: 8.0.x
+        dotnet-version: 6.0.x
     
     - name: Install dependencies
       run: dotnet restore "${{ github.workspace }}/mywebapp/mywebapp.sln"
@@ -32,15 +32,14 @@ jobs:
     
     - name: Test
       run: |
-        dotnet test "${{ github.workspace }}/mywebapp/mywebapp.sln" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
+        dotnet test "${{ github.workspace }}/mywebapp/mywebapp.sln" --no-restore --verbosity normal  --logger "trx;LogFileName=test-results.trx"
 
     - name: Test Report
-      uses: dorny/test-reporter@v3
-      if: ${{ !cancelled() }}
-      continue-on-error: true
+      uses: dorny/test-reporter@v1.5.0
+      if: success() || failure()    # run this step even if previous step failed
       with:
-        name: XUnit Tests
-        path: ${{ github.workspace }}/mywebapp/tests/TestResults/*.trx
+        name: XUnit Tests            # Name of the check run which will be created
+        path: ${{ github.workspace }}/mywebapp/tests/TestResults/*.trx    # Path to test results
         reporter: dotnet-trx
       
     - name: Publish
@@ -50,112 +49,11 @@ jobs:
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4
       with:
+        # Artifact name
         name: mywebappbuildartifacts
+        # A file, directory or wildcard pattern that describes what to upload
         path: mywebapp/**
+        # The desired behavior if no files are found using the provided path.
         if-no-files-found: error
+        # Duration after which artifact will expire in days. 0 means using default retention.
         retention-days: 90
-
-  deploy-DEV:
-    name: "Deploy To Azure DEV env"
-    runs-on: ubuntu-latest
-    needs:
-      - build-app
-    environment:
-      name: 'DEMO05_DEV'
-      url: 'https://mywebapp-actions-dev.azurewebsites.net'
-
-    steps:
-    - uses: actions/checkout@v5
-      
-    - name: Setup .NET 8
-      uses: actions/setup-dotnet@v5
-      with:
-        dotnet-version: 8.0.x
-    
-    - name: 'Login via Azure CLI'
-      uses: azure/login@v2
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-    
-    - name: Download a Build Artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: 'mywebappbuildartifacts'
-        path: 'mywebappbuildartifacts'
-   
-    - name: 'Deploy to Azure Web App'
-      uses: azure/webapps-deploy@v3
-      with: 
-        app-name: mywebapp-actions
-        package: 'mywebappbuildartifacts'
-        slot-name: 'dev'   
-        
-  deploy-QA:
-    name: "Deploy To Azure QA env"
-    runs-on: ubuntu-latest
-    needs:
-      - build-app
-    environment:
-      name: 'DEMO05_QA'
-      url: 'https://mywebapp-actions-qa.azurewebsites.net'
-
-    steps:
-    - uses: actions/checkout@v5
-      
-    - name: Setup .NET 8
-      uses: actions/setup-dotnet@v5
-      with:
-        dotnet-version: 8.0.x
-    
-    - name: 'Login via Azure CLI'
-      uses: azure/login@v2
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-    
-    - name: Download a Build Artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: 'mywebappbuildartifacts'
-        path: 'mywebappbuildartifacts'
-   
-    - name: 'Deploy to Azure Web App'
-      uses: azure/webapps-deploy@v3
-      with: 
-        app-name: mywebapp-actions
-        package: 'mywebappbuildartifacts'
-        slot-name: 'qa'   
-        
-  deploy-PROD:
-    name: "Deploy To Azure PROD env"
-    runs-on: ubuntu-latest
-    needs:
-      - deploy-DEV
-      - deploy-QA
-    environment:
-      name: 'DEMO05_PROD'
-      url: 'https://mywebapp-actions.azurewebsites.net'
-
-    steps:
-    - uses: actions/checkout@v5
-      
-    - name: Setup .NET 8
-      uses: actions/setup-dotnet@v5
-      with:
-        dotnet-version: 8.0.x
-    
-    - name: 'Login via Azure CLI'
-      uses: azure/login@v2
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-    
-    - name: Download a Build Artifact
-      uses: actions/download-artifact@v4
-      with:
-        name: 'mywebappbuildartifacts'
-        path: 'mywebappbuildartifacts'
-   
-    - name: 'Deploy to Azure Web App'
-      uses: azure/webapps-deploy@v3
-      with: 
-        app-name: mywebapp-actions
-        package: 'mywebappbuildartifacts'
